title = "Citizen Labs"
baseURL = "https://citizenlabs.org"
languageCode = "en-us"
theme = "ananke"
publishDir = "public"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
Paginate = 3
googleAnalytics = "UA-115392197-1"
HUGO_ENV = production
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "img/favicon/favicon-32x32.png"
  description = "Empowering citizens to improve their communities and local government."
  defaultKeywords = ["citizen labs", "open data", "grand rapids", "open source", "open budget"]
  github = "https://github.com/citizenlabsgr" # add your github profile name
  twitter = "https://twitter.com/citizen_labs" # add your twitter profile
  email = "hello@citizenlabs.org"
  meetup = "https://www.meetup.com/Citizen-Labs/"
  slack = "http://slackin-citizenlabs.herokuapp.com/"
  facebook = "https://www.facebook.com/citizenlabs"
  instagram = "https://www.instagram.com/citizenlabs/"
  youtube = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-orange"
  recent_posts_number = 3
  # removed empty featured image so that sub pages would not automatically include featured image:   featured_image =
  logo = "img/common/Logo-02.png"
  body_classes = "helvetica bg-near-white"

[params.get_involved]
    enable = true

[menu]

  [[menu.main]]
      name = "Join Us"
      title = "Join Us"
      weight = -140
      identifier = "join_us"
      url = "/join_us/"

  [[menu.main]]
      name = "Our Work"
      title = "Our Work"
      weight = -130
      identifier = "our_work"
      url = "/our_work/"

  [[menu.main]]
      name = "About"
      title = "About"
      weight = -110
      identifier = "about"
      url = "/about/"

  [[menu.main]]
      name = "Sponsors"
      title = "Sponsors"
      parent = "about"
      identifier = "sponsors"
      weight = -110
      url = "/about/sponsors/"

  [[menu.main]]
      name = "News"
      title = "News"
      weight = -120
      identifier = "post"
      url = "/post/"

  [[menu.main]]
      name = "Contact"
      title = "Contact"
      weight = -100
      identifier = "contact"
      url = "/contact/"
