baseURL: http://something-fresh.org/
languageCode: en-us
title: Citizen Labs
theme: hugo-fresh
MetaDataFormat: yaml
googleAnalytics: UA-115392197-1
#Disables warningss
disableKinds:
 -taxonomy
 -taxonomyTerm


params:
 # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  defaultKeywords: ["citizen labs", "open data", "grand rapids", "open source", "open budget"]
  description: Empowering citizens to improve their communities and local government.
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/CL_Logo-04-orange.png
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Let's Make Our Community Better Together
    # Hero subtitle (optional)
    subtitle:
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "join"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - heart
    - grwebdev
    - pyladies
    - wmrn
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Join Us
    url: /join
  - title: Our Work
    url: /our_work
  - title: About
    sublinks:
    - title: Code of Conduct
      url: /about/conduct
    - title: Sponsors
      url: /about/sponsor
    - title: Our Team
      url: /about/team
  - title: News
    url: /
  - title: Contact
    url: /
    button: true
  section1:
    title: Great power comes
    subtitle: with great responsibility
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: CL_Logo.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/citizenlabsgr
      # Icons are from Font Awesome
      icon: github
    - link: https://www.meetup.com/Citizen-Labs/
      icon: meetup
    - link: https://www.facebook.com/citizenlabs
      icon: facebook
    - link: https://twitter.com/citizen_labs
      icon: twitter
    bulmalogo: false
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
